constellation_brands/constellation_brands/urls.py
from django.contrib import admin
from django.urls import path, include

from .views import (
    HomeView
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", HomeView.as_view(), name="home"),

    # use allauth to handle user registration/login/logout.
    path('accounts/', include('allauth.urls')),

    path("reservations/", include(("reservations.urls", "reservations"), namespace="reservations"),),
    path("reservations/", include(("reservations.urls", "reservation"), namespace="reservation"),),
    path("wineries/", include(("wineries.urls", "wineries"), namespace="wineries"),),
]

constellation_brands/reservations/urls.py
from django.urls import path

from .views import (
    Home,
    CreateReservation,
    DetailReservation,
    UpdateReservation,
    DeleteReservation,
)

urlpatterns = [
    path("", Home.as_view(), name="home"),
    path("create/", CreateReservation.as_view(), name="create"),
    path("read/", DetailReservation.as_view(), name="detail"),
    path("update/<int:pk>/", UpdateReservation.as_view(), name="update"),
    path("delete/<int:pk>/", DeleteReservation.as_view(), name="delete"),
]

constellation_brands/wineries/urls.py
from django.urls import path

from .views import Home

urlpatterns = [
    path("", Home.as_view(), name="home"),
]

constellation_brands/reservations/models.py
from django.db import models
from django.contrib.auth.models import User

# Import winery. One to Many relationship from reservation to Winery.
from wineries.models import Winery

class Reserveration(models.Model):

    # Fields
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    reservation_location = models.ForeignKey(Winery, on_delete=models.CASCADE)
    reservation_time = models.DateField()

    def __str__(self):
        return f"self.user at self.reservation.name"

constellation_brands/wineries/models.py
from django.db import models

class Winery(models.Model):

    # Fields
    name = models.CharField(max_length=128)
    slogan = models.CharField(max_length=128)
    description = models.TextField()
    website = models.URLField(max_length=200)

    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.name.title()}"

constellation_brands/reservations/forms.py
from django import forms

from .models import Reserveration

class ReservationForm(forms.ModelForm):

    class Meta:
        model = Reserveration
        fields = [
            "reservation_location",
            "reservation_time"
        ]
        widgets = {
            'reservation_time': forms.DateInput(attrs={'type': 'date'})
        }

constellation_brands/constellation_brands/views.py
from django.views.generic import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin

class HomeView(LoginRequiredMixin, TemplateView):
    template_name = 'constellation_brands/home.html'

constellation_brands/reservations/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.views.generic import DetailView, ListView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.urls import reverse_lazy
from django.contrib import messages

from .models import Reserveration
from .forms import ReservationForm

class Home(LoginRequiredMixin, ListView):
    template_name = "reservations/home.html"
    model = Reserveration

    def get_queryset(self):
        """
        # (R. Friel - February 25, 2021)
        Ensure only the user's reservations are returned.
        """
        return Reserveration.objects.filter(user=self.request.user)


class CreateReservation(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    template_name = "reservations/create.html"
    model = Reserveration

    form_class = ReservationForm

    success_url = reverse_lazy("reservations:home")
    success_message = "Your reservation has been created."

    def form_valid(self, form):
        """
        # (R. Friel - February 25, 2021)
        Ensure that the user is added to the form so the association between user and reservation is made.
        """
        form.instance.user = self.request.user
        return super().form_valid(form)


class UpdateReservation(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    template_name = "reservations/update.html"
    model = Reserveration

    form_class = ReservationForm

    success_url = reverse_lazy("reservations:home")
    success_message = "You successfully saved changes to your reservation."


class DetailReservation(LoginRequiredMixin, DetailView):
    template_name = "reservations/detail.html"
    model = Reserveration
    form_class = ReservationForm


class DeleteReservation(LoginRequiredMixin, SuccessMessageMixin, DeleteView):
    template_name = "reservations/delete.html"
    model = Reserveration
    success_url = reverse_lazy("reservations:home")
    success_message = "Your selected reservation has been deleted."

    def delete(self, request, *args, **kwargs):
        messages.success(self.request, self.success_message)
        return super(DeleteReservation, self).delete(request, *args, **kwargs)

constellation_brands/wineries/views.py
from django.views.generic.list import ListView
from django.contrib.auth.mixins import LoginRequiredMixin

from .models import Winery

class Home(LoginRequiredMixin, ListView):
    template_name = 'wineries/home.html'
    model = Winery

constellation_brands/constellation_brands/templates/constellation_brands/base.html
<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <!-- Bootstrap core CSS -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

        <!-- Constellation Brands Favicon  -->
        <link rel="icon" type="image/png" href="https://d8ejoa1fys2rk.cloudfront.net/5.0.5/includes/img/icons/cbrands.ico">
        <title>Constellation Brands Wineries</title>
    </head>



    <body>

        <nav class="navbar navbar-light" style="background-color: #e3f2fd;">

            <a class="navbar-brand" href="https://www.cbrands.com/">
                <img src="https://res-3.cloudinary.com/crunchbase-production/image/upload/c_lpad,f_auto,q_auto:eco/v1468059967/darfogb7qv4nu7q8sdvw.png" width="30" height="30" class="d-inline-block align-top" alt="">
                Constellation Brands
            </a>

                <ul class="nav justify-content-end">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'home' %}"">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'wineries:home' %}">Wineries</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'reservations:home' %}">Reservations</a>
                    </li>

                </ul>

        </nav>


        {% block content %}
        {% endblock content %}

    </body>



    <!-- Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

</html>

constellation_brands/constellation_brands/templates/constellation_brands/home.html
{% extends 'constellation_brands/base.html' %}
{% load static %}

{% block content %}
<div class="container-fluid">
    <div class="card card-cascade narrower">

        <!-- Card image -->
        <div class="view view-cascade gradient-card-header">
            <h2 class="mb-0 font-weight-bold">{{ title_text | title }} Welcome to Constellation Brands!</h2>
        </div>

        <div>
            <p>
                Please take a moment to view our wineries! Then please make a reservation to sample some delicious wines there.
            </p>
        </div>

    </div>
</div>
{% endblock content %}

constellation_brands/constellation_brands/templates/reservations/create.html
{% extends 'constellation_brands/base.html' %}

{% csrf_token %}
{% load crispy_forms_tags %}

{% block content %}

<div class="content-selection">
    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">

            {{ form|crispy }}

        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-info" type="submit">
                Create Reservation
            </button>
        </div>
    </form>
</div>



{% endblock content %}

constellation_brands/constellation_brands/templates/reservations/delete.html
{% extends "constellation_brands/base.html" %}
{% load crispy_forms_tags %}

{% block content %}

    <div class="content-selection" xmlns="http://www.w3.org/1999/html">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">
                    Delete {{ object.reservation_location.name }} reservation?
                </legend>
            </fieldset>

            <div class="form-group">
                <button class="btn btn-outline-danger" type="submit">
                    Delete Reservation
                </button>
            </div>
        </form>
    </div>

{% endblock content %}

constellation_brands/constellation_brands/templates/reservations/detail.html
{% extends 'constellation_brands/base.html' %}

{% csrf_token %}
{% load crispy_forms_tags %}

{% block content %}

    <div class="card" style="max-width: 18rem;">
        <div class="card-body">
            <h5 class="card-title">Reservation</h5>
            <p class="card-text">Location: {{ object.reservation_location.name }}</p>
            <p class="card-text">Time: {{ object.reservation_time }}</p>
        </div>
        <ul class="list-group list-group-flush">
            <li class="list-group-item">Winery Slogan: {{ object.reservation_location.slogan }}</li>
            <li class="list-group-item">Winery Description: {{ object.reservation_location.description }}</li>
            <li class="list-group-item">Winery Website: {{ object.reservation_location.website }}</li>
        </ul>
        <div class="card-body">
            <a href="{% url 'reservations:update' object.pk %}" class="btn btn-outline-warning btn-sm" role="button">Update</a>
            <a href="{% url 'reservations:delete' object.pk %}" class="btn btn-outline-danger btn-sm" role="button">Delete</a>
        </div>
    </div>

{% endblock content %}

constellation_brands/constellation_brands/templates/reservations/home.html
{% extends 'constellation_brands/base.html' %}


{% block content %}

    {% for object in object_list %}

        <div class="card" style="max-width: 18rem;">
            <div class="card-body">
                <h5 class="card-title">Reservation</h5>
                <p class="card-text">Location: {{ object.reservation_location.name }}</p>
                <p class="card-text">Time: {{ object.reservation_time }}</p>
            </div>
            <ul class="list-group list-group-flush">
                <li class="list-group-item">Winery Slogan: {{ object.reservation_location.slogan }}</li>
                <li class="list-group-item">Winery Website: {{ object.reservation_location.website }}</li>
            </ul>
            <div class="card-body">
                <a href="{% url 'reservations:update' object.pk %}" class="btn btn-outline-warning btn-sm" role="button">Update</a>
                <a href="{% url 'reservations:delete' object.pk %}" class="btn btn-outline-danger btn-sm" role="button">Delete</a>
            </div>
        </div>

    {% endfor %}

    <div class="card" style="max-width: 18rem;">
        <div class="card-body">
            <p class="card-text">Create a new reservation?</p>
            <p class="card-text">
                <a href="{% url 'reservation:create' %}" class="btn btn-primary btn-lg active" role="button" aria-pressed="true">Create Reservation</a>
            </p>
        </div>
    </div>

{% endblock content %}

constellation_brands/constellation_brands/templates/reservations/update.html
{% extends 'constellation_brands/base.html' %}

{% load crispy_forms_tags %}

{% block content %}

    <div class="content-selection">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">
                    Update {{ object.reservation_location.name }} reservation
                </legend>
                {{ form|crispy }}

            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">
                    Update Reservation
                </button>
            </div>
        </form>
    </div>

{% endblock content %}

constellation_brands/constellation_brands/templates/wineries/home.html
{% extends 'constellation_brands/base.html' %}
{% load static %}

{% block content %}


{% for object in object_list %}

    <div class="card" style="width: 18rem;">
        <div class="card-body">
            <h5 class="card-title">{{object.name}}</h5>
            <h6 class="card-subtitle mb-2 text-muted">{{object.slogan}}</h6>
            <p class="card-text">{{object.description}}</p>
            <a href="{{object.website}}" class="card-link">Website</a>
        </div>
    </div>

{% endfor %}

{% endblock content %}